services:
  app:
    build: .
    container_name: delivery-api-rabay
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    # A aplicação poderá acessar o banco pelo hostname 'db'
    # Profile dev ativado para usar configurações MySQL

  db:
    image: mysql:8.0
    container_name: delivery-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: deliverydb
      MYSQL_USER: deliveryuser
      MYSQL_PASSWORD: deliverypass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --max-connections=100
    # O banco estará acessível na rede interna como 'db:3306'
    # Scripts de inicialização executados automaticamente

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: delivery-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: deliveryuser
      PMA_PASSWORD: deliverypass
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
    # Painel de controle MySQL acessível em http://localhost:8081
    # Login automático configurado com credenciais do MySQL

  redis:
    image: redis:7-alpine
    container_name: delivery-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass redispass

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local