services:
  app:
    build: .
    container_name: delivery-api-rabay
    ports:
      - "8080:8080"
    depends_on:
      - db
      - prometheus
      - grafana
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    # A aplicação poderá acessar o banco pelo hostname 'db'
    # Profile dev ativado para usar configurações MySQL
    # Limites de recursos para melhor gerenciamento de containers
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Configuração de verificação de saúde
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    container_name: delivery-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: deliverydb
      MYSQL_USER: deliveryuser
      MYSQL_PASSWORD: deliverypass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --max-connections=100
    # O banco estará acessível na rede interna como 'db:3306'
    # Scripts de inicialização executados automaticamente
    # Limites de recursos para banco de dados
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: delivery-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: deliveryuser
      PMA_PASSWORD: deliverypass
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
    # Painel de controle MySQL acessível em http://localhost:8081
    # Login automático configurado com credenciais do MySQL

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_MODE=console
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local